openapi: 3.0.3
info:
  title: TD1 specification Onboarding API
  description: specification onboarding process
  version: 1.0.0
paths:
  /students:
    post:
      summary: Create a new student account
      operationId: createStudent
      requestBody:
        description: Student account details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input

  /students/{studentId}:
    get:
      summary: Get student details by ID
      operationId: getStudent
      parameters:
        - name: studentId
          in: path
          description: ID of the student
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Student details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found

    delete:
      summary: Delete student by ID
      operationId: deleteStudent
      parameters:
        - name: studentId
          in: path
          description: ID of the student
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Student deleted successfully
        '404':
          description: Student not found

    patch:
      summary: Update student details by ID
      operationId: updateStudent
      parameters:
        - name: studentId
          in: path
          description: ID of the student
          required: true
          schema:
            type: string
      requestBody:
        description: Updated student account details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input
        '404':
          description: Student not found

  /teachers:
    post:
      summary: Create a new teacher account
      operationId: createTeacher
      requestBody:
        description: Teacher account details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teacher'
      responses:
        '201':
          description: Teacher account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
        '400':
          description: Invalid input

  /teachers/{teacherId}:
    get:
      summary: Get teacher details by ID
      operationId: getTeacher
      parameters:
        - name: teacherId
          in: path
          description: ID of the teacher
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Teacher details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
        '404':
          description: Teacher not found

    delete:
      summary: Delete teacher by ID
      operationId: deleteTeacher
      parameters:
        - name: teacherId
          in: path
          description: ID of the teacher
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Teacher deleted successfully
        '404':
          description: Teacher not found

    patch:
      summary: Update teacher details by ID
      operationId: updateTeacher
      parameters:
        - name: teacherId
          in: path
          description: ID of the teacher
          required: true
          schema:
            type: string
      requestBody:
        description: Updated teacher account details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teacher'
      responses:
        '200':
          description: Teacher details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
        '400':
          description: Invalid input
        '404':
          description: Teacher not found

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: lova
        birthdate:
          type: string
          example: é_

    Teacher:
      type: object
      properties:
        idTeacher:
          type: string
          example: T1
        nameTeacher:
          type: string
          example: madame
        birthdate:
          type: string
          example: 1990
